swagger: "2.0"
info:
  version: "1.0.0"
  title: "User Management API"
paths:
  /api/user/register:
    post:
      summary: Register a new user
      consumes:
        - multipart/form-data
      parameters:
        - name: username
          in: formData
          description: User's username
          required: true
          type: string
        - name: password
          in: formData
          description: User's password
          required: true
          type: string
        - name: file
          in: formData
          description: Profile image file
          required: true
          type: file
        - name: firstname
          in: formData
          description: User's first name
          required: true
          type: string
        - name: lastname
          in: formData
          description: User's last name
          required: true
          type: string
        - name: gender
          in: formData
          description: User's gender
          required: true
          type: string
        - name: city
          in: formData
          description: User's city
          required: false
          type: string
        - name: usertype
          in: formData
          description: User's type
          required: true
          type: string
      responses:
        200:
          description: User registration successful
        409:
          description: Duplicate entry (username already exists)
        500:
          description: Internal server error
  /api/user/login:
    post:
      summary: User login
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Login request body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Successful login
        500:
          description: Internal server error

  /api/user/resetPassword:
    post:
      summary: Reset user password
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Reset password request body
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
              newpassword:
                type: string
      responses:
        200:
          description: Password reset successful
        500:
          description: Internal server error

  /api/user/updateProfile:
    post:
      summary: Update user profile
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Update profile request body
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
              firstname:
                type: string
              lastname:
                type: string
              gender:
                type: string
              city:
                type: string
      responses:
        200:
          description: Profile update successful
        500:
          description: Internal server error

  /api/user/getUserProfile:
    post:
      summary: Get user profile
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Get user profile request body
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
      responses:
        200:
          description: Successful profile retrieval
        500:
          description: Internal server error

  /api/user/forgotPassword:
    post:
      summary: Forgot password
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Forgot password request body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        200:
          description: Password reset instructions sent
        500:
          description: Internal server error
  